/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CharacterClassCreationDto {
  description: string;
  maxHealth?: number;
  name: string;
}
