/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CharacterClassDto {
  description: string;
  id: string;
  maxHealth: number;
  name: string;
}
