/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HealthDto } from '../models/health-dto';
import { MinimalCharacterClassDto } from '../models/minimal-character-class-dto';
export interface CharacterDto {
  class: MinimalCharacterClassDto;
  dateOfBirth: string;
  experience: number;
  gold: number;
  health: HealthDto;
  id: string;
  name: string;
  userId: string;
}
