/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiV1CharactersIdDelete$Params {
  id: string;
  'X-Api-Version'?: string;
}

export function apiV1CharactersIdDelete(http: HttpClient, rootUrl: string, params: ApiV1CharactersIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1CharactersIdDelete.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('X-Api-Version', params['X-Api-Version'], {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiV1CharactersIdDelete.PATH = '/api/v1/Characters/{id}';
