/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CharacterDto } from '../../models/character-dto';

export interface ApiV1CharactersIdGet$Json$Params {
  id: string;
  'X-Api-Version'?: string;
}

export function apiV1CharactersIdGet$Json(http: HttpClient, rootUrl: string, params: ApiV1CharactersIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CharacterDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1CharactersIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('X-Api-Version', params['X-Api-Version'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CharacterDto>;
    })
  );
}

apiV1CharactersIdGet$Json.PATH = '/api/v1/Characters/{id}';
