/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CharacterCreationDto } from '../../models/character-creation-dto';

export interface ApiV1CharactersPost$Params {
  'X-Api-Version'?: string;
      body: CharacterCreationDto
}

export function apiV1CharactersPost(http: HttpClient, rootUrl: string, params: ApiV1CharactersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1CharactersPost.PATH, 'post');
  if (params) {
    rb.header('X-Api-Version', params['X-Api-Version'], {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiV1CharactersPost.PATH = '/api/v1/Characters';
